using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;
using System.IO;

namespace _0._10sApp
{
    class mainLogic
    {
        public mainLogic()
        {

        }

        public void Start()
        {
            //Process pytonLigths = new Process();

            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = @"C:\Users\Aganya.D\Desktop\GitT\0.10s\pyton\dist\PythonApplication1\PythonApplication1.exe";
            start.Arguments = "";// string.Format("\"{0}\" \"{1}\"", cmd, args);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardInput = true;
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            string read = "";
            using (Process process = Process.Start(start))
            {
                StreamReader reader = process.StandardOutput;
                StreamWriter writer = process.StandardInput;
                Console.WriteLine("start----------");
                do
                {
                    
                    try
                    {
                        string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                        string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                        read += result;
                        Console.Write(read);
                    }
                    catch (Exception ex)
                    {
                        Console.Write(ex.Message);
                        break;
                    }
                    
                } while (!read.Contains("Enter Command...."));


                try
                {
                    writer.WriteLine("1,2,3,4;1,2,3,4;1,2,3,4;1,2,3,4;1,2,3,4"); 
                }
                catch (Exception ex)
                {
                    Console.Write(ex.Message);
                }

                try
                {
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    Console.Write(result);
                }
                catch (Exception ex)
                {
                    Console.Write(ex.Message);
                }





            }


            while (true)
            {

            }

        }

    }
    class Program
    {
        static void Main(string[] args)
        {
            while (true)
            {
                mainLogic mainApp = new mainLogic();
                mainApp.Start();
            }
        }
    }


}
